services:
  flask:
    build: .
    container_name: flask_app
    expose:
      - "5000"
    volumes:
      - ./static:/app/static

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "8081:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static
    depends_on:
      - flask

